name: Sysdig - Build, scan and upload SARIF report

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: "38 16 * * 0"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build the Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag "${{ github.repository }}:latest" \
            .

      - name: Sysdig Secure Inline Scan
        id: scan
        uses: sysdiglabs/scan-action@768d7626a14897e0948ea89c8437dd46a814b163
        with:
          image-tag: ${{ github.repository }}:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: https://us2.app.sysdig.com
          dockerfile-path: ./Dockerfile
          input-type: docker-daemon
          ignore-failed-scan: true
          run-as-user: root

      - name: Upload SARIF report to GitHub
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.scan.outputs.sarifReport }}
          category: sysdig
